# Generated by Django 2.2.12 on 2020-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(default='value', max_length=120),
            preserve_default=False,
        ),
    ]
