# Generated by Django 2.2.12 on 2020-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
